### ISSUE TITLE
Release 1.4.0 on PGXN?

### ISSUE THREAD

**Issue by theory** [omniti-labs/pg_jobmon#12]
Latest on PGXN is 1.3.2; time to push out 1.4.0? Is it released yet?

**Comment by keithf4** [comment]
Fixed a syntax error in the META file and created a release from my own fork to push up.

**Comment by devrimgunduz** [comment]
Why it is not released here? My spec files are broken now :(

**Comment by keithf4** [comment]
I've pushed the 1.4.0 version out to PGXN and created a PR for tagging the release here (https://github.com/omniti-labs/pg_jobmon/pull/13)

Will need to have someone that maintains this repo merge it in and then tag it as well.  @xzilla @payals @vventirozos

**Comment by keithf4** [comment]
Version 1.4.1 has been pushed up to PGXN
