### ISSUE TITLE
Int overflow in jobmon.add_step

### ISSUE THREAD

**Issue by Anthares** [omniti-labs/pg_jobmon#14]
Hello here :)

Today found a lot of error mails of one of our maintenance job : 
```
2021-02-03 07:50:01,443 ERROR Unexpected error: value "2147483984" is out of range for type integer
CONTEXT:  SQL statement "SELECT step_id FROM public.dblink('dbname=*** user=***','SELECT jobmon._autonomous_add_step (8888,''Create archival tables'')',TRUE) t (step_id int)"
PL/pgSQL function jobmon.add_step(bigint,text) line 15 at EXECUTE SQL statement "select jobmon.add_step(__job_id, 'Create archival tables')"
PL/pgSQL function archival.archival_job(timestamp without time zone,timestamp without time zone,integer) line 44 at SQL statement
```

All jobmon's tables have bigint IDs, but call to dblink in `jobmon.add_step` uses an int as return type.
Which, in my case, just crashed because we have generated more than an int of job logs.

I patched it at my side, but seems something that could hurt someone else :)
Best regards

**Comment by keithf4** [comment]
Apologies for not seeing this sooner. I've made a PR to fix this issue. If you'd like you can pull version 1.4.1 from my fork.

**Comment by keithf4** [comment]
Version 1.4.1 has been merged into this repository. Thank you for reporting the issue!
