### ISSUE TITLE
Cannot create partition job_log and job_detail

### ISSUE THREAD

**Issue by phuonghuynguyen** [omniti-labs/pg_jobmon#19]
Hi, I have installed jobmon extension and it works properly.
However, when I try to partition table job_log and job_detail with this execution:

`postgres=# SELECT partman.create_parent(p_parent_table := 'jobmon.job_log', p_control := 'start_time', p_type := 'native', p_interval := 'monthly', p_jobmon := 'false');`

I get:

        ERROR:  When using native partitioning, you must have created the given parent table as ranged (not list) partitioned already. Ex: CREATE TABLE ... PARTITION BY RANGE ...)
        CONTEXT: PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,text) line 131 at RAISE 
        DETAIL:
        HINT:
        CONTEXT:  PL/pgSQL function partman.create_parent(text,text,text,text,text[],integer,text,text,boolean,text,text,text[],boolean,text,boolean,text) line 807 at RAISE

It's an expected behaviour since that type of those table is `table`, not `partitoned table` as output below:

        postgres=# \dt jobmon.*
                      List of relations 
        Schema |         Name          | Type  |  Owner
        --------+-----------------------+-------+----------
        jobmon | dblink_mapping_jobmon | table | postgres
        jobmon | job_check_config      | table | postgres
        jobmon | job_check_log         | table | postgres
        jobmon | job_detail            | table | postgres
        jobmon | job_log               | table | postgres
        jobmon | job_status_text       | table | postgres
        (6 rows)

So my question is how can I partition those tables? Tks in advance.

**Comment by keithf4** [comment]
Answered this question over on the pg_partman repository. Unfortunately, it's difficult to manage this extension with pg_partman.

https://github.com/pgpartman/pg_partman/issues/491#issuecomment-1320145762

**Comment by phuonghuynguyen** [comment]
closed
