### ISSUE TITLE
dump/restore issue

### ISSUE THREAD

**Issue by akorotkov** [omniti-labs/pg_jobmon#2]
I've faced following issue when dump/restore this extension.
- Table `job_status_text` is initialized with data by `CREATE EXTENSION` command.
- pg_dump dumps `CREATE EXTENSION` command as well as `job_status_text` contents.
- When restoring dump I get unique violation because `job_status_text` was initialied twice: during `CREATE EXTENSION` command and during `COPY` statement.

Actually, this error could be safely ignored. But it discourages users.
Is it supposed that user can add his own value to `job_status_text`? Or is it just fixed dictionary?

**Comment by keithf4** [comment]
Unfortunately, I don't think there's anything I can do about this. The way extensions currently are, they are not well designed for extensions that have table data. Most especially ones where the extension adds its own data that users can than manipulate. `job_status_text` is meant to be user-changeable, but it also needs some default values added.

Right now an extension table can either be set to never dump data during a pg_dump (the default, and what the `job_log` & `job_details` tables are set to ) or always dump data, even on a schema-only dump (what `job_status_text` is set to).

So, while I can't really fix it, thanks for bringing this up! I'll see about adding some notes in the documentation. Me, and many others, have brought up this shortcoming, but I'm not aware of any fixes in the works yet. This is just more ammunition for my side of the argument. :)

**Comment by akorotkov** [comment]
Can the default values in `job_status_text` be altered by user? If not, then we can divide default and user-defined values into two tables and build view over them.

**Comment by keithf4** [comment]
Default values can be altered, yes, so just splitting with a view on top doesn't make it any easier to manage. Perhaps something a little fancier that, instead of joining the two tables, would override the defaults. Will see if I can figure something out. Or you're free to do a push request as well that I can evaluate. :)

**Comment by keithf4** [comment]
Version 1.3.3 includes Pull Request https://github.com/omniti-labs/pg_jobmon/pull/5 which fixes this issue.

**Comment by xzilla** [comment]
Given this bug is fixed in a released version, ISTM we should close this ticket.
