### ISSUE TITLE
Use `pg_settings` for port?

### ISSUE THREAD

**Issue by j16sdiz** [omniti-labs/pg_jobmon#3]
It is possible to initialize the port from `pg_settings` or `inet_server_port()` ?
The current default can be confusing if the server is running on non-default port

**Comment by keithf4** [comment]
Please see the README for installation instructions. If you're running on a non-default port, all you have to do is enter that value in the `dblink_mapping_jobmon` table.

**Comment by j16sdiz** [comment]
@keithf4 , I am doing that already.
But I think the installer (?) can get that from the settings.
Would be great if it can do it automatically.

**Comment by keithf4** [comment]
I see what you mean. Guess it could do that, but the username (and maybe password) still has to be set, and it's setting the same table and same row anyway.
Added this to my notes to see about adding it if/when another feature comes up to add. Not sure when that will be tho.

**Comment by keithf4** [comment]
Since I have this covered in the readme, and username has to be set anyway, I'm just going to leave things as they are. Probably be just as confusing, if not more, when someone gets an error trying to insert a new row vs having to update the current one already there.
