### ISSUE TITLE
dblink ERROR:  could not establish connection

### ISSUE THREAD

**Issue by chamnan** [omniti-labs/pg_jobmon#4]
Dear All,

I've faced problem that dblink could not establish connection when no host param. Postgresql 9.5.1
Am I configured wrong?

    ERROR:  could not establish connection
    DETAIL:  FATAL:  Peer authentication failed for user "test_login"
    SELECT zz_ext_dblink.dblink_connect('dbname=test user=test_login password=123456');
    
    IT's OK:
    SELECT zz_ext_dblink.dblink_connect('dbname=test host=192.168.4.50 user=test_login password=123456');
    or
    SELECT zz_ext_dblink.dblink_connect('dbname=test host=localhost user=test_login password=123456');

In my pg_hba.conf:
    
    # TYPE  DATABASE       USER            ADDRESS                 METHOD
    local   test         test_login                                md5
===
    SELECT zz_ext_partman.create_parent('test.part_test', 'col1', 'id', '10');

    ERROR:  could not establish connection
    DETAIL:  FATAL:  Peer authentication failed for user "test_login"
    CONTEXT:  SQL statement "SELECT job_id FROM zz_ext_dblink.dblink('dbname=test user=test_login password=123456','SELECT zz_ext_jobmon._autonomous_add_job (''postgres'',''PARTMAN CREATE PARENT: test.part_test'',5184)',TRUE) t (job_id int)"
    PL/pgSQL function add_job(text) line 14 at EXECUTE
    SQL statement "SELECT zz_ext_jobmon.add_job('PARTMAN CREATE PARENT: test.part_test')"
    PL/pgSQL function zz_ext_partman.create_parent(text,text,text,text,text[],integer,boolean,text,boolean,boolean,boolean,boolean) line 488 at EXECUTE

**Comment by keithf4** [comment]
Are you sure that's the entirety of your pg_hba.conf file? If you have any entries higher that have "peer" set as the authentication method, they will override anything below them.

**Comment by chamnan** [comment]
I see, it work now.
Thank you for your suggestion.
