### ISSUE TITLE
Minimum version of PostgreSQL required is 9.4.0 

### ISSUE THREAD

**Issue by mrbf** [omniti-labs/pg_jobmon#6]
My postgreSQL version is 9.4.7.

>#SELECT version();
> PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-4), 64-bit

But when I run 'make install' it shows 'Makefile:24: *** Minimum version of PostgreSQL required is 9.4.0.  Stop.'.
What's can be wrong with my server?

**Comment by mrbf** [comment]
I've solve problem with changing path as:
>PATH=/usr/pgsql-9.5/bin:$PATH
>export PATH

**Comment by keithf4** [comment]
Just to clarify for myself, this is an error from pg_partman's Makefile. Is that where you actually saw the error?

**Comment by mrbf** [comment]
Yes, This error was from pg_partman's Makefile.

**Comment by amoltarte** [comment]
I already have 9.6.12 but getting the same error.
Please help me, I am on Windows 10 x64
Getting error
makefile:42: *** Minimum version of PostgreSQL required is 9.4.0.  Stop.

Everything is in path like postgresql\9.6\Data\;postgresql\9.6\Bin\ etc.

**Comment by fingoldo** [comment]
C:\Users\Administrator\pg_partman>pg_config
BINDIR = C:/PROGRA~1/POSTGR~1/11/bin
DOCDIR = C:/PROGRA~1/POSTGR~1/11/doc
HTMLDIR = C:/PROGRA~1/POSTGR~1/11/doc
INCLUDEDIR = C:/PROGRA~1/POSTGR~1/11/include
PKGINCLUDEDIR = C:/PROGRA~1/POSTGR~1/11/include
INCLUDEDIR-SERVER = C:/PROGRA~1/POSTGR~1/11/include/server
LIBDIR = C:/PROGRA~1/POSTGR~1/11/lib
PKGLIBDIR = C:/PROGRA~1/POSTGR~1/11/lib
LOCALEDIR = C:/PROGRA~1/POSTGR~1/11/share/locale
MANDIR = C:/Program Files/PostgreSQL/11/man
SHAREDIR = C:/PROGRA~1/POSTGR~1/11/share
SYSCONFDIR = C:/Program Files/PostgreSQL/11/etc
PGXS = C:/Program Files/PostgreSQL/11/lib/pgxs/src/makefiles/pgxs.mk
CONFIGURE = --enable-thread-safety --enable-nls --with-ldap --with-openssl --with-ossp-uuid --with-libxml --with-libxslt --with-icu --with-tcl --with-perl --with-python
CC = not recorded
CPPFLAGS = not recorded
CFLAGS = not recorded
CFLAGS_SL = not recorded
LDFLAGS = not recorded
LDFLAGS_EX = not recorded
LDFLAGS_SL = not recorded
LIBS = not recorded
VERSION = PostgreSQL 11.7

C:\Users\Administrator\pg_partman>make install
The system cannot find the path specified.
Makefile:42: *** Minimum version of PostgreSQL required is 9.4.0.  Stop.

pg_partman version is fresh (just cloned from git). Maybe you can at least add more debug information in the error message, at least what version your install script is getting?
