### ISSUE TITLE
Error while trying to install pg_jobmon

### ISSUE THREAD

**Issue by sharadov** [omniti-labs/pg_jobmon#7]
I am trying to install pg_jobmon on Postgres 9.5.5.
After downloading and extracting the package and running make install I get the error below -
/bin/sh /usr/lib64/pgsql/pgxs/src/makefiles/../../config/install-sh -c -m 644 ./doc/pg_jobmon.md '/usr/share/doc/pgsql/contrib'

Any ideas?

**Comment by keithf4** [comment]
Where did you obtain a package for pg_jobmon? That also doesn't look like an error, just an installation command.

**Comment by sharadov** [comment]
From here - https://github.com/omniti-labs/pg_jobmon

**Comment by keithf4** [comment]
Just running the install on 9.5.12, the line you posted is just the last line of the installation, not an error message
```
keith@mint ~/Projects/pg_jobmon $ psql --version
psql (PostgreSQL) 9.5.12
keith@mint ~/Projects/pg_jobmon $ make install
cat sql/tables/tables.sql sql/functions/job_monitor_trigger.sql sql/functions/show_job.sql sql/functions/check_job_status.sql sql/functions/show_detail.sql sql/functions/sql_job.sql sql/functions/show_job_like.sql sql/functions/close_job.sql sql/functions/add_job.sql sql/functions/fail_job.sql sql/functions/show_job_status.sql sql/functions/job_log_clear.sql sql/functions/sql_step.sql sql/functions/auth.sql sql/functions/job_check_log_escalate_trig.sql sql/functions/add_step.sql sql/functions/update_step.sql sql/functions/show_running.sql sql/functions/cancel_job.sql > sql/pg_jobmon--1.3.3.sql
/bin/mkdir -p '/opt/pgsql9512/share/extension'
/bin/mkdir -p '/opt/pgsql9512/share/extension'
/bin/mkdir -p '/opt/pgsql9512/share/doc/extension'
/usr/bin/install -c -m 644 .//pg_jobmon.control '/opt/pgsql9512/share/extension/'
/usr/bin/install -c -m 644 .//updates/pg_jobmon--1.1.1--1.1.2.sql .//updates/pg_jobmon--1.1.0--1.1.1.sql .//updates/pg_jobmon--1.0.1--1.0.2.sql .//updates/pg_jobmon--0.4.3--0.4.4.sql .//updates/pg_jobmon--1.1.3--1.2.0.sql .//updates/pg_jobmon--0.3.2--0.3.3.sql .//updates/pg_jobmon--0.3.4--0.3.5.sql .//updates/pg_jobmon--0.1.2--0.2.0.sql .//updates/pg_jobmon--0.3.1--0.3.2.sql .//updates/pg_jobmon--0.3.0--0.3.1.sql .//updates/pg_jobmon--0.4.2--0.4.3.sql .//updates/pg_jobmon--1.3.2--1.3.3.sql .//updates/pg_jobmon--0.4.4--0.4.5.sql .//updates/pg_jobmon--1.2.0--1.3.0.sql .//updates/pg_jobmon--0.4.1--0.4.2.sql .//updates/pg_jobmon--1.3.1--1.3.2.sql .//updates/pg_jobmon--1.0.2--1.1.0.sql .//updates/pg_jobmon--1.3.0--1.3.1.sql .//updates/pg_jobmon--1.0.0--1.0.1.sql .//updates/pg_jobmon--0.3.5--0.4.0.sql .//updates/pg_jobmon--1.1.2--1.1.3.sql .//updates/pg_jobmon--0.4.0--0.4.1.sql .//updates/pg_jobmon--0.2.0--0.2.1.sql .//updates/pg_jobmon--0.3.3--0.3.4.sql .//updates/pg_jobmon--0.4.5--1.0.0.sql .//sql/pg_jobmon--1.3.3.sql  '/opt/pgsql9512/share/extension/'
/usr/bin/install -c -m 644 .//doc/pg_jobmon.md '/opt/pgsql9512/share/doc/extension/'
```
After this, you will have to log into the database and run CREATE EXTENSION.

Also, I highly recommend getting upgraded to the latest minor release of 9.5. You are now 7 patch versions behind and upgrading this only requires a restart.  Both security and data integrity related issues have been fixed - https://why-upgrade.depesz.com/show?from=9.5.5&to=9.5.12

**Comment by sharadov** [comment]
Thanks Keith, that was it. I had to copy some files over to my /extension dir and it installed successfully.

**Comment by keithf4** [comment]
Shouldn't have had to copy any files over if the `make install` ran properly. I'd be more concerned why you had to do that to get things working.

**Comment by sharadov** [comment]
When I tried to 
`CREATE EXTENSION pg_jobmon SCHEMA jobmon;`
I got the error below
ERROR:  could not open extension control file "/opt/pgsql/9.5.5.std/share/extension/pg_jobmon.control": No such file or directory
Postgres in my case is installed in the above directory while I extracted pg_jobmon package to /opt/pgsql/pg_jobmon.
I copied the file over and it let me create the extension.

**Comment by keithf4** [comment]
It sounds like pg_jobmon is being built against the system version that was installed and not your custom location in `/opt`

`/usr/share/doc/pgsql/contrib`

The above location in your original post is what makes me think that. Not quite as big a deal since both seem to be 9.5, but if you ever have conflicting major versions installed, that may break things. Make sure the directory where your custom install is done is before the system location in your PATH. That's why you can see my install against my `/opt` location works.

**Comment by sharadov** [comment]
Interesting. I use an environment file for postgres and in there:
export PATH=/opt/pgsql/current/bin:$PATH
Current points to 9.5.5.std.
And echo $PATH gives me this -
usr/local/java/jdk/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/java/jdk/bin:/usr/local/java/ant/bin:/usr/local/java/maven/bin:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

Am not sure why it's still going against the system version?

**Comment by keithf4** [comment]
Your echo'd $PATH doesn't have your `/opt` location in it

**Comment by sharadov** [comment]
Thanks!
